export const FETCH_OPEN_WEATHER = 'FETCH_OPEN_WEATHER';
export const FETCH_OPEN_WEATHER_CURRENT_SUCCESS = 'FETCH_OPEN_WEATHER_CURRENT_SUCCESS';
export const FETCH_OPEN_WEATHER_CURRENT_ERROR = 'FETCH_OPEN_WEATHER_CURRENT_ERROR';
export const FETCH_OPEN_WEATHER_FORECAST_SUCCESS = 'FETCH_OPEN_WEATHER_FORECAST_SUCCESS';
export const FETCH_OPEN_WEATHER_FORECAST_ERROR = 'FETCH_OPEN_WEATHER_FORECAST_ERROR';

export const FETCH_APIXU = 'FETCH_APIXU';
export const FETCH_APIXU_SUCCESS = 'FETCH_APIXU_SUCCESS';
export const FETCH_APIXU_ERROR = 'FETCH_APIXU_ERROR';

export const GET_GEOLOCATION_SUCCESS = 'GET_GEOLOCATION_SUCCESS';
export const GET_GEOLOCATION_ERROR = 'GET_GEOLOCATION_ERROR';

export const SET_UNITS = 'SET_UNITS';

export const GET_SAMPLE_COLOR = 'GET_SAMPLE_COLOR';
export const SET_SAMPLE_COLOR = 'SET_SAMPLE_COLOR';
export const GET_SAMPLE_COLOR_ERROR = 'GET_SAMPLE_COLOR_ERROR';
